### ISSUE TITLE
There has a compile issue

### ISSUE THREAD

**Issue by max-liulin** [itberrios/CV_tracking#2]
```
    6 timestamps = pd.read_csv(timestamp_path, 
    7                          header=None, 
    8                          squeeze=True).astype(object) \
    9                                       .apply(lambda x: x.split(' ')[1]) 
    11 # Get Hours, Minutes, and Seconds
---> 12 hours = ser.apply(lambda x: x.split(':')[0]).astype(np.float64)
    13 minutes = ser.apply(lambda x: x.split(':')[1]).astype(np.float64)
    14 seconds = ser.apply(lambda x: x.split(':')[2]).astype(np.float64)

NameError: name 'ser' is not defined
```
Which package should be imported as 'ser' ?

**Comment by itberrios** [comment]
Hi Max,

It looks like I forgot to change variable names in an update. The name 'ser' was an old variable name and was replaced with timestamps.. I have pushed the changes. Let me know if this works for you.

**Comment by max-liulin** [comment]
Thanks, it works now.
Would you share how to generate accurate calibration file for imu and gps sensor in this repo? I'm confusing this part.

**Comment by itberrios** [comment]
Glad to hear that it works now.

For the GPS/IMU sensor you should be able to use the data contained in the oxts files without any manipulation, for this repo, I was able to use the raw GPS/IMU data with no issue.

Here's some more clarification. The GPS/INS is not completely time aligned to the other sensors such as the cameras and LiDAR. For example timestamp 1 could be 5.001 for the GPS/IMU and 5.004 for the LiDAR. According to the KITTI paper the worst time alignment is roughly 5ms, this time misalignment appears negligible in the data.

If you want to, you can account for the time misalignment by interpolating the data across all the times for all the sensors that you are using and then resample the data at times from a single sensor such as the camera. The benefit is that you obtain potentially more accurate measurements at the current time stamp. However in this repo I didn't implement the interpolation, since it seems like the accuracy gains weren't worth it.

Hope this helps, let me know if you have any more questions.

**Comment by itberrios** [comment]
I'm going to go ahead and close this. Please comment if anything else comes up.
